Add support for structured curved mesh visualization in 2D
trixi-framework/Trixi2Vtk.jl pull request #31
Opened 2021-04-13 06:33 UTC by sloede

2021-04-14 10:40 UTC, sloede commented
@bennibolm @erik-f @NichtLucas 2D waved flag seems to work now. Starting `julia --project` in this branch, using
```julia
julia> using Trixi2Vtk

julia> Trixi.trixi2vts("../main-Trixi.jl/out/solution_000041.h5")
```
yields the following VTS visualization in ParaView: 

![image](https://user-images.githubusercontent.com/3637659/114697409-2decb780-9d1e-11eb-80df-3a37aeeb0987.png)

2021-04-14 10:53 UTC, sloede commented
So, loading the mapping function from the string in the file is still somewhat brittle. With local ad-hoc modifications, I am able to also visualize the result of `examples/2d/elixir_euler_free_stream_curved.jl`:
![image](https://user-images.githubusercontent.com/3637659/114699286-642b3680-9d20-11eb-9d6f-a8758201311a.png)

2021-04-22 14:09 UTC, erik-f commented
We now plot `CurvedMesh` data on Lagrange cells, which allows for perfect resolution with only `n_nodes` visualization nodes. However, the nonlinear subdivision level in ParaView needs to be turned up to get proper results.

We removed duplicate code and reused most of the code for `TreeMesh` data.

It is possible to use more visualization nodes than DG nodes, which is useful for curved cells. While ParaView shows the exact interpolation if the Lagrange nodes are equidistant, it shows different results otherwise. This means that the data on curved cells is not exactly the correct interpolation. Using more visualization nodes somehow mitigates this problem.

2021-05-13 04:39 UTC, sloede reviewed
In general, I think this looks already pretty good!

@erik-f @bennibolm @NichtLucas I hope I can leave these changes to you?

2021-05-13 04:39 UTC, sloede commented on src/convert.jl
> +    @timeit "read mesh" mesh = Trixi.load_mesh_serial(meshfile; RealT=Float64, n_cells_max=100_000)
```suggestion
    @timeit "read mesh" mesh = Trixi.load_mesh_serial(meshfile; RealT=Float64)
```
Can be omitted with Trixi v0.3.31

2021-05-13 04:39 UTC, sloede commented on Project.toml
> +Trixi = "0.3.30"
```suggestion
Trixi = "0.3.31"
```
to get rid of `n_cells_max`

2021-05-13 04:39 UTC, sloede commented on src/vtktools.jl
> +  # end
```suggestion
```
Obsolete?

2021-05-13 04:39 UTC, sloede commented on src/vtktools.jl
> +  #                                                               vtk_celldata_cells)
```suggestion
```
Obsolete?

2021-05-13 04:39 UTC, sloede commented on src/vtktools.jl
> +function calc_node_coordinates!(node_coordinates::AbstractArray{<:Any, 4}, f, nodes, mesh)
AFAICT, this routine is only useful for the structured mesh and applies for 2D. Thus, I am wondering if one could mention this in a comment to this function (and for the next `calc_node_coordinates!`)

2021-05-13 04:39 UTC, sloede commented on src/vtktools.jl
> +# Convert coordinates and level information to a list of points and VTK cells (2D version)
This method and the next one are only used for the curved stuff, right? Could we please have a comment that mentions this?

2021-05-13 06:10 UTC, andrewwinters5000 requested changes

2021-05-13 06:10 UTC, andrewwinters5000 commented on src/convert.jl
> +               (default: number of DG nodes for CurvedMesh, twice the number of DG nodes for TreeMesh).
```suggestion
               (default: number of DG nodes for CurvedMesh or UnstructuredQuadMesh,
                         twice the number of DG nodes for TreeMesh).
```

2021-05-13 06:10 UTC, andrewwinters5000 commented on src/vtktools.jl
> +# Create and return VTK grids that are ready to be filled with data (CurvedMesh version)
```suggestion
# Create and return VTK grids that are ready to be filled with data (CurvedMesh/UnstructuredQuadMesh version)
```

2021-05-13 08:23 UTC, andrewwinters5000 approved these changes

2021-05-15 09:36 UTC, bennibolm commented
All suggestion should be implemented now. `n_max_cells=0` is still needed because we didn't add a default value there.

2021-05-15 09:39 UTC, sloede commented
Can you please mark all resolved comments as such? And why do we still need n_cells_max=0?

2021-05-15 10:00 UTC, bennibolm commented
I can't, it's not my PR. But all should be resolved now (maybe except the one with `n_cells_max`?).
In Trixi's [load_mesh_serial](https://github.com/trixi-framework/Trixi.jl/blob/ff549a5e67a7685f2ad3c97a0694c756160d79b4/src/mesh/mesh_io.jl#L150-160) we just added the `max(n_cells, n_cells_max)` but no default value for `n_cells_max`. We just added it for `load_mesh` but that's a restart file there.

2021-05-19 14:49 UTC, merged